meta:
  timezone: "Europe/Rome"
  run_days: [1, 15]
  window_days: 14

include_keywords:
  - "(?i)thinkpad"
  - "(?i)lenovo"
  - "(?i)windows 12"
  - "(?i)windows 11"
  - "(?i)major update|patch|aggiornamento"
  - "(?i)copilot\\+"
  - "(?i)24h2|hudson valley"
  - "(?i)gen\\s?(5|6|7)"
  - "(?i)leak|roadmap|rumor|release"
  - "(?i)fcc|fccid"
  - "(?i)\\b3c\\b|china compulsory certification|ccc"
  - "(?i)\\bred\\b|radio equipment directive|ce mark|marcatura ce"
  - "(?i)802\\.11be|wifi\\s*7"
  - "(?i)\\b(20|21)[A-Z0-9]{2}\\b"

exclude_keywords:
  - "(?i)ideapad|legion|gaming|xbox|playstation|dlc|assassin|mirage"
  - "(?i)coupon|expired|giveaway|promo|offerta|sconto"
  - "(?i)shitpost|meme|random|cat"

news_sources:
  - url: "https://www.notebookcheck.net/rss/news.xml"
  - url: "https://news.lenovo.com/feed/"
  - url: "https://www.hdblog.it/rss/"
  - url: "https://blogs.windows.com/feed/"
  - url: "https://www.windowscentral.com/feed"
  - url: "https://www.neowin.net/news/rss"
  - url: "https://techreport.com/feed/"
  - url: "https://slashdot.org/rss/slashdotMain"
  # fonti cinesi
  - url: "https://www.ithome.com/rss/"
  - url: "https://rss.mydrivers.com/rss.aspx?Tid=1"
  # certificazioni (FCC/3C)
  - url: "https://fccid.io/feed"
