name: Build Notebook Report (MD only)

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Forza commit anche senza diff"
        required: false
        default: "false"
  schedule:
    - cron: "0 7 1,15 * *" # 1 e 15 del mese, 07:00 UTC

permissions:
  contents: write

concurrency:
  group: build-notebook-report
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Python deps
        run: pip install -r scripts/requirements.txt

      - name: Run tracker (MD + JSON + copia nel browser)
        run: |
          python3 scripts/tracker.py \
            --config scripts/config.yaml \
            --since-days 14

      - name: Detect changes (MD/JSON)
        id: detect
        shell: bash
        run: |
          git add report/notebook-tracking.md report/news.json notebook-dashboard/public/news.json
          if git diff --staged --quiet -- report/notebook-tracking.md report/news.json notebook-dashboard/public/news.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.detect.outputs.changed == 'true' || github.event.inputs.force == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update MD/JSON report [skip ci]" || echo "No changes to commit"
          git push || true

      # --- opzionale: build del browser locale (commentato) ---
      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20"
      #     cache: "npm"  # caching integrato per npm
      # - name: Build dashboard
      #   working-directory: notebook-dashboard
      #   run: |
      #     npm ci
      #     npm run build
      # ----------------------------------------------------------
