name: Check Lenovo T16

on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:

permissions:
  contents: write   # allow this workflow to push commits

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        run: python scripts/check_lenovo.py

      - name: Commit and push history.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add history.md
          git commit -m "Update history.md [skip ci]" || echo "No changes to commit"
          git push
